Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.network "private_network", ip: "192.168.33.3"
  config.vm.hostname = "kafka.mylab.com"
  config.vm.provider "virtualbox" do |v|
   v.memory = 4096
   v.cpus = 2
   end
  end 