version: '2'

services:
  # https://github.com/confluentinc/schema-registry
  confluent-schema-registry:
    image: confluentinc/cp-schema-registry:3.2.1
    network_mode: host
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 192.168.33.3:2181/kafka
      SCHEMA_REGISTRY_LISTENERS: http://192.168.33.3:8081
      # please replace this setting by the IP of your web tools server
      SCHEMA_REGISTRY_HOST_NAME: "192.168.33.3"
    restart: always

  # https://github.com/confluentinc/kafka-rest
  confluent-rest-proxy:
    image: confluentinc/cp-kafka-rest:3.2.1
    network_mode: host
    environment:
      KAFKA_REST_BOOTSTRAP_SERVERS: 192.168.33.3:9092
      KAFKA_REST_ZOOKEEPER_CONNECT: 192.168.33.3:2181/kafka
      KAFKA_REST_LISTENERS: http://192.168.33.3:8082/
      KAFKA_REST_SCHEMA_REGISTRY_URL: http://192.168.33.3:8081/
      # please replace this setting by the IP of your web tools server
      KAFKA_REST_HOST_NAME: "192.168.33.3"
    depends_on:
      - confluent-schema-registry
    restart: always

  # https://github.com/Landoop/kafka-topics-ui
  kafka-topics-ui:
    image: landoop/kafka-topics-ui:0.9.2
    network_mode: host
    environment:
      KAFKA_REST_PROXY_URL: http://192.168.33.3:8082
      PROXY: "TRUE"
    depends_on:
      - confluent-rest-proxy
    restart: always
